version: '2'

services:
  web: 
    build: .
    #image: py3:celery
    depends_on:
      - redis
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: python /code/proj/manage.py runserver 0.0.0.0:5000

  redis:
    image: redis:3.0


