version: '2'

services:
  web: &web
    build: .
    depends_on:
      - redis
    volumes:
      - ./proj:/code
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: python /code/manage.py runserver 0.0.0.0:5000

  celeryworker:
    <<: *web
    depends_on:
      - redis
    env_file:
      - .env
    ports: []
    command: celery -A proj worker -l info

  celerybeat:
    <<: *web
    depends_on:
      - redis
    env_file:
      - .env
    ports: []
    command: celery -A proj beat -l info

  flower:
    <<: *web
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "5555:5555"
    command: celery -A proj flower --address=0.0.0.0 -l info
  redis:
    image: redis:3.0


